import 'dart:async';

import '../controller/chat_flow_controller.dart';

class ExplainResult {
  final String sessionId;
  final String explanation;

  ExplainResult({
    required this.sessionId,
    required this.explanation,
  });
}

class MishkaAiService {
  /// Example: "http://127.0.0.1:8000"
  /// This is a DUMMY implementation - ignores baseUrl
  final String baseUrl;

  MishkaAiService({this.baseUrl = 'http://127.0.0.1:8000'});

  /// Simulate PDF explanation without backend
  /// Returns: { session_id, explanation }
  Future<ExplainResult> explainPdf({
    required String pdfPath,
    required String summaryLevel, // "simple" | "detailed"
  }) async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 1200));

    final sessionId = "dummy-${DateTime.now().millisecondsSinceEpoch}";
    final explanation = _buildExplanation(summaryLevel);

    return ExplainResult(
      sessionId: sessionId,
      explanation: explanation,
    );
  }

  /// Simulate chat endpoint
  /// POST /chat(session_id, message) -> { response }
  Future<String> chat({
    required String sessionId,
    required String message,
  }) async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 800));

    // Simple deterministic response based on message
    if (message.toLowerCase().contains('hello')) {
      return 'Hello! I\'m Mishka, your study partner. How can I help you today?';
    }
    if (message.toLowerCase().contains('how') || message.toLowerCase().contains('what')) {
      return 'I can help you with quizzes, flashcards, and mind maps based on this content!';
    }
    if (message.toLowerCase().contains('explain')) {
      return 'This is a comprehensive study guide. Feel free to ask me anything specific about the material.';
    }
    if (message.toLowerCase().contains('thank')) {
      return 'You\'re welcome! Keep up the great work! 📚';
    }
    return 'Great question! That\'s an important concept. Would you like me to explain it further?';
  }

  /// Simulate tool generation endpoint
  /// POST /generate-tools(session_id, tool_type, complexity)
  /// Returns tool data as JSON map
  Future<Map<String, dynamic>> generateTool({
    required String sessionId,
    required StudyAction action,
    required String complexity, // "Simple" | "Intermediate" | "Advanced"
  }) async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 1000));

    switch (action) {
      case StudyAction.quiz:
        return _dummyQuiz(sessionId, complexity);
      case StudyAction.flashcards:
        return _dummyFlashcards(sessionId, complexity);
      case StudyAction.mindmap:
        return _dummyMindmap(sessionId, complexity);
      case StudyAction.summarize:
        return _dummySummary(sessionId, complexity);
    }
  }

  // ===========================
  // DUMMY DATA GENERATORS
  // ===========================

  Map<String, dynamic> _dummyQuiz(String sessionId, String complexity) {
    // Always return 10 questions (requirement: "Fixed total questions: 10")
    final questions = [
      {
        "questionText": "What is an interrupt in an embedded system?",
        "options": [
          "A memory storage unit",
          "An event that stops normal CPU execution",
          "A type of microcontroller",
          "A programming error"
        ],
        "correctOptionIndex": 1,
      },
      {
        "questionText": "Which type of interrupt is generated by a timer overflow?",
        "options": [
          "External interrupt",
          "Internal interrupt",
          "PORTB change interrupt",
          "Serial interrupt"
        ],
        "correctOptionIndex": 1,
      },
      {
        "questionText": "Which interrupt is always high priority in PIC18F452?",
        "options": [
          "INT0",
          "INT1",
          "INT2",
          "PORTB change interrupt"
        ],
        "correctOptionIndex": 0,
      },
      {
        "questionText": "Which bit indicates that an interrupt has occurred?",
        "options": [
          "IE",
          "IP",
          "IF",
          "GIE"
        ],
        "correctOptionIndex": 2,
      },
      {
        "questionText": "What must be true for an interrupt to be detected?",
        "options": [
          "Only the flag bit is set",
          "Only the enable bit is set",
          "Both enable and flag bits are set",
          "The CPU must be idle"
        ],
        "correctOptionIndex": 2,
      },
      {
        "questionText": "Which register enables interrupt priority levels?",
        "options": [
          "INTCON",
          "PIR1",
          "RCON",
          "PIE1"
        ],
        "correctOptionIndex": 2,
      },
      {
        "questionText": "High-priority interrupts are vectored to which address?",
        "options": [
          "0000H",
          "0008H",
          "0018H",
          "0020H"
        ],
        "correctOptionIndex": 1,
      },
      {
        "questionText": "Which pins generate PORTB change interrupts?",
        "options": [
          "RB0–RB2",
          "RB1–RB3",
          "RB4–RB7",
          "RB0–RB7"
        ],
        "correctOptionIndex": 2,
      },
      {
        "questionText": "What must be done to the interrupt flag inside the ISR?",
        "options": [
          "Set it",
          "Ignore it",
          "Clear it",
          "Toggle it"
        ],
        "correctOptionIndex": 2,
      },
      {
        "questionText": "What happens when interrupt priority is disabled?",
        "options": [
          "Only high-priority interrupts work",
          "All interrupts go to address 0018H",
          "All interrupts have the same priority",
          "Interrupts stop working"
        ],
        "correctOptionIndex": 2,
      },
    ];

    return {
      "tool_type": "quiz",
      "title": "Knowledge Check - 10 Questions",
      "questions": questions,
      "totalQuestions": 10,
    };
  }

  Map<String, dynamic> _dummyFlashcards(String sessionId, String complexity) {
    // Return 3-4 flashcards (requirement: "Count: 2–4 only")
    final cards = [
      {
        "id": "card_1",
        "title": "Interrupt Definition",
        "image": "assets/images/flashcard_item1.png",
        "front": "What is an interrupt?",
        "back": "An interrupt is an event that causes the CPU to stop normal execution and execute a specific service routine."
      },
      {
        "id": "card_2",
        "title": "Interrupt Control Bits",
        "image": "assets/images/flashcard_item2.png",
        "front": "What are IE, IF, and IP bits?",
        "back": "IE enables the interrupt, IF indicates the interrupt occurred, and IP selects high or low priority."
      },
      {
        "id": "card_3",
        "title": "Interrupt Priority",
        "image": "assets/images/flashcard_item3.png",
        "front": "What is special about INT0?",
        "back": "INT0 is always a high-priority interrupt and has no priority bit."
      },
      {
        "id": "card_4",
        "title": "PORTB Interrupts",
        "image": "assets/images/saved_card_1.png",
        "front": "When does a PORTB change interrupt occur?",
        "back": "It occurs when any pin from RB4 to RB7 changes its input state."
      },
    ];

    return {
      "tool_type": "flashcards",
      "title": "Interrupts Flashcards",
      "cards": cards,
    };
  }

  Map<String, dynamic> _dummyMindmap(String sessionId, String complexity) {
    return {
      "tool_type": "mind_maps",
      "title": "Interrupts Overview",
      "root": "Interrupts",
      "nodes": [
        {
          "title": "Types of Interrupts",
          "children": [
            "Internal Interrupts",
            "External Interrupts",
            "Timer Interrupts",
            "Peripheral Interrupts"
          ]
        },
        {
          "title": "Control Bits",
          "children": [
            "Enable Bit (IE)",
            "Flag Bit (IF)",
            "Priority Bit (IP)"
          ]
        },
        {
          "title": "Priority System",
          "children": [
            "High Priority",
            "Low Priority",
            "Vector Address 0008H",
            "Vector Address 0018H"
          ]
        },
        {
          "title": "Special Cases",
          "children": [
            "INT0 Always High Priority",
            "PORTB Change Interrupt",
            "Flag Cleared in ISR"
          ]
        }
      ]
    };
  }

  Map<String, dynamic> _dummySummary(String sessionId, String complexity) {
    return {
      "tool_type": "summaries",
      "title": "Generated Summary",
      "summary": _buildExplanation('simple'),
    };
  }

  // ===========================
  // HELPERS
  // ===========================

  String _buildExplanation(String summaryLevel) {
    if (summaryLevel.toLowerCase() == 'simple') {
      return """
📘 Embedded Systems – Interrupts (Simple Explanation)

An interrupt is an event that forces the CPU to stop its normal program
execution and handle an urgent task.

🔹 Types of Interrupts:
• Internal interrupts: generated inside the microcontroller
  (e.g. timer overflow)
• External interrupts: generated by external signals
  (e.g. I/O pin state change)

🔹 PIC18F452 Interrupt Sources:
• External interrupts (INT0, INT1, INT2)
• PORTB change interrupts (RB4–RB7)
• Timer interrupts (Timer 0–3)
• Serial communication interrupts
• ADC and CCP interrupts

🔹 Interrupt Control:
Each interrupt has:
• Enable bit (IE) → turns interrupt on/off
• Flag bit (IF) → indicates interrupt occurred
• Priority bit (IP) → high or low priority

🔹 Important Notes:
• Flag bits must be cleared in software
• INT0 is always high priority
• High-priority interrupts can interrupt low-priority ones

This lecture explains how interrupts are configured, prioritized,
and handled in PIC microcontrollers.
""";
    } else {
      return """
📘 Embedded Systems – Interrupts (Detailed Explanation)

An interrupt is a mechanism that allows the CPU to temporarily suspend
normal execution to respond to time-critical events.

🔹 Interrupt Sources in PIC18F452:
• External interrupts on RB0/INT0, RB1/INT1, RB2/INT2
• PORTB change interrupts (RB4–RB7)
• Timer overflow interrupts (TMR0–TMR3)
• Serial communication interrupts (TX, RX)
• ADC conversion complete
• CCP modules

🔹 Interrupt Control Bits:
Each interrupt source is controlled by:
1) IE (Interrupt Enable)
2) IF (Interrupt Flag)
3) IP (Interrupt Priority)

An interrupt is recognized only if:
• Enable bit = 1
• Flag bit = 1
• Global interrupt enable is active

🔹 Priority System:
• High-priority interrupts vector to address 0x0008
• Low-priority interrupts vector to address 0x0018
• High-priority interrupts can interrupt low-priority routines
• Priority can be disabled, making all interrupts equal

🔹 Registers Used:
• RCON → enables priority structure
• INTCON, INTCON2, INTCON3
• PIR1, PIR2 → interrupt flags
• PIE1, PIE2 → interrupt enables
• IPR1, IPR2 → interrupt priorities

🔹 External Interrupt Behavior:
• Edge-triggered (rising or falling)
• INT0 has fixed high priority
• INT1 and INT2 are configurable

🔹 PORTB Change Interrupt:
• Triggered by any change on RB4–RB7
• One enable bit and one flag for all pins

🔹 Practical Examples:
The lecture demonstrates configuring INT1 for:
• Falling-edge, low priority
• Rising-edge, high priority

This provides a complete foundation for interrupt handling
in embedded systems.
""";
    }
  }
}


